name: Auto Update IPTV Source

on:
  schedule:
    - cron: '0 20 * * *' # 北京时间凌晨 4 点
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install aiohttp

      - name: Run Auto Repair
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.email "cusco888@outlook.com"
          git config --global user.name "CUSCO888"
          git add output/*.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto Repair Playlists [$(date '+%Y-%m-%d')]"
          git push
